apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-metrics
  namespace: monitoring
  labels:
    name: nginx-ingress
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - nginx-ingress
  selector:
    matchLabels:
       app: nginx-ingress
  endpoints:
  - interval: 30s
    port: metrics