apiVersion: v1
kind: Pod
metadata:
  name: network-tools
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: armsultan/network-tools:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always